platform :ios, '11.0'
use_frameworks!
target 'ExUI_Example' do
  pod 'ExUI', :path => '../'
  pod 'ExLog', :git => 'https://github.com/chorokichi/ExLog.git'

  target 'ExUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
    pod 'Nimble-Snapshots' , '~> 6.3.0', :inhibit_warnings => true
  end
end
