platform :ios, '11.0'
use_frameworks!
target 'ExUI_Example' do
  pod 'ExUI', :path => '../'
  pod 'ExLog', :git => 'https://github.com/chorokichi/ExLog.git'

  target 'ExUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
    pod 'Nimble-Snapshots' , '~> 6.3.0', :inhibit_warnings => true
  end
  
  #https://github.com/PaoloCuscela/Cards/issues/10#issuecomment-416783744
  post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
          '$(FRAMEWORK_SEARCH_PATHS)'
          ]
          installer.pods_project.build_configurations.each do |config|
              config.build_settings.delete('CODE_SIGNING_ALLOWED')
              config.build_settings.delete('CODE_SIGNING_REQUIRED')
          end
      end
  end
end

# Workaround for Cocoapods issue #7606
#post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#        config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
#        config.build_settings.delete('CODE_SIGNING_REQUIRED')
#    end
#end

